### ISSUE TITLE
parser doesn't recognize comments not at beginning of line (syntax error returned)

### ISSUE THREAD

**Issue by martindemko** [sybila/biodivine-ctl#6]
for both (bio and ctl) files

**Comment by daemontus** [comment]
Can you give an example?

I just tried this one

```
VARS: foo //comment
VARS: goo #comment
//comment VARS: foo
#comment VARS: goo
```
for the .bio file (not a valid model, but valid syntax) and the parser was ok with it (recognized the first two VARS statements, withouth the trailing comment and completely discarded the other two)

Also - what version were you using? The latest one (published 2.1.2017) or something older?

**Comment by martindemko** [comment]
It causes problem in 'EQ:' lines and also in ctl file:
Syntax error at ':?' in C:\Users\User\skola\pracovny\R\biodivineGUI\..\Temp\prop.963704.ctl:5 (java.lang.IllegalStateException)

**Comment by daemontus** [comment]
Something like this?
```
EQ: x = y + z //foo
```
But the :? syntax error looks like you still have the old version of ctl parser somewhere.
